[package]
name = "debuginfod-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
path-absolutize = "3.1.1"
rpm-rs = { git = "https://github.com/marxin/rpm-rs.git", branch = "dev" }
